### ISSUE TITLE
解析成功后报错

### ISSUE THREAD

**Issue by Philae994** [xfmujie/douyin#2]
正在解析……

解析成功！
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\douyin-master\main.py", line 50, in <module>
    print(GREEN + '标题：' + RESET + res['data']['title'])
                                  ~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by xfmujie** [comment]
我看下分享链接

**Comment by Philae994** [comment]
> 我看下分享链接

你好表哥，分享链接如下：


9.28 05/11 v@s.rE mDu:/ 复制打开抖音，看看【奶盖会发光的作品】《一念关山》主创见面会完整版 # 一念关山 # 一... https://v.douyin.com/i8B82tb6/

**Comment by xfmujie** [comment]
> > 我看下分享链接
> 
> 你好表哥，分享链接如下：
> 
> 9.28 05/11 [v@s.rE](mailto:v@s.rE) mDu:/ 复制打开抖音，看看【奶盖会发光的作品】《一念关山》主创见面会完整版 # 一念关山 # 一... https://v.douyin.com/i8B82tb6/

后端已修复，可以正常使用了

**Comment by Philae994** [comment]
> > > 我看下分享链接
> > 
> > 
> > 你好表哥，分享链接如下：
> > 9.28 05/11 [v@s.rE](mailto:v@s.rE) mDu:/ 复制打开抖音，看看【奶盖会发光的作品】《一念关山》主创见面会完整版 # 一念关山 # 一... https://v.douyin.com/i8B82tb6/
> 
> 后端已修复，可以正常使用了

 感谢表哥
